### PR TITLE
Add template to extend pytest_addoption

### PR DESCRIPTION
**Pull request by yeganer**
This template shows how to extend pytest_functions defined in
astropy.tests.pytest_plugins similiar to a super call in a class.

### CODE REVIEW

**Comment by yeganer** [comment]
This is related to issue #175

**Comment by pllim** [comment]
Maybe extend the comments a little more to suggest how one might use the extra option?

**Comment by yeganer** [comment]
@pllim I extended the comments. Do you want an example how the additional option could be used, too?
Somethink like this?
```
slow = pytest.mark.skipif(
    not pytest.config.getoption("--slow"),
    reason="need --slow option to run"
)
```

**Comment by pllim** [comment]
Thanks. I meant something more like "after you added this option, this is how you add the code in your test to use that option for your test..." This is because people who use the template have varying Python proficiency, so we should be as user-friendly as possible.

**Comment by yeganer** [comment]
There are two ways one could show this.
The first is using the decorator I posted in the above comment.
The second one would be to create a fixture. This would have the benefit of showing the use of fixtures, too.
The fixture approach has the benefit that the solution is available in all tests where the `@slow` decorator needs to be implemented or imported in every file that uses it.

Which solution would you prefer to be in the example?

**Comment by pllim** [comment]
Ideally both, so user can choose. But if that is too much trouble, links to existing doc on how to accomplish them are sufficient.

**Comment by pllim** [comment]
I found a need for this and found out the following:
```python
>>> import packagename
>>> packagename.test(slow=True)  # Error
>>> packagename.test(args='--slow')  # Okay
```

This should be documented as well, along with the `@slow` decorator usage mentioned in http://doc.pytest.org/en/latest/example/simple.html.

**Comment by bsipocz** [comment]
We're moving over to cookicutter, so I'm closing old unresolved PRs. Please reopen against the cookicutter branch if you feel this is still relevant.

**Pull request closed without merging**
