### PR TITLE
Use xenial for Travis CI

### PR DESCRIPTION
**Pull request by pllim**
https://docs.travis-ci.com/user/reference/xenial/

### CODE REVIEW

**Comment by bsipocz** [comment]
Hmm, is this better than the default? How often the best way changes? E.g. packages using the template may not be as quick to change it when this becomes obsolete.

**Comment by astrofrog** [comment]
Is there a way to specify to use the latest distribution? (using xenial is needed for Python 3.7)

**Comment by pllim** [comment]
Huh, maybe `xenial` is the default now... I see that astropy core uses xenial and no `dist` is specified there. It is unclear to me how to specify latest... Did I miss something in https://docs.travis-ci.com/user/reference/overview/ ? Maybe we should be using `bionic` instead?

**Comment by bsipocz** [comment]
I think it doesn't matter much. We're not that sensitive to the compiler stuff and besides only use the very basics. 
If there are any reasons to change it in repos (getting 20s quicker builds, etc) I'm on board, my only resistance is with the template. Changing the CI config files will never be easy with auto PRs, and thus being specific now may bite back in the end (e.g. tons of repos still don't use stages, and apt install unnecessarily as they don't keep up with the template changes).

**Comment by pllim** [comment]
Yeah, good point.

**Comment by saimn** [comment]
xenial is the default now: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

**Pull request closed without merging**
