### PR TITLE
Fix typo: cmdclassd -> cmdclass

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by pllim** [comment]
I am not sure it is a typo, the trailing `d` might stand for dictionary.

**Comment by lpsinger** [comment]
`package_info` is a dictionary but does not end with a `d`.

**Comment by bsipocz** [comment]
@astrofrog might remember as he wrote that line 6+ years ago.

**Comment by pllim** [comment]
Looks like @astrofrog named it 6 years ago. Maybe he knows.

**Comment by pllim** [comment]
Haha, jinx! 😉

**Pull request merged**
