### PR TITLE
fix install_requires bug

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
This makes install requires not a question we ask the users. Any objections to this?

**Comment by astrofrog** [comment]
Why not allow users to set that?

**Comment by Cadair** [comment]
it's still changeable once the template is rendered, it's just not a question asked during the "wizard" bit on running "cookiecutter".
My main reason for this is how many people when initially templating a package know what their install deps are?

**Comment by Cadair** [comment]
bump

**Pull request merged**
