### PR TITLE
DEBUG: try different conda versions to see when things broke

### PR DESCRIPTION
**Pull request by astrofrog**
⚠️ **This should never be merged** ⚠️ 

cc @bsipocz - this will allow us to identify the last working version

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - wow, this is impressive. This case I'm removing the debug commit I've made in one of the PRs here.

**Comment by bsipocz** [comment]
astropy travis is rather in a traffic jam, so a copy of this branch is being tested on my fork: https://travis-ci.org/bsipocz/package-template

**Comment by astrofrog** [comment]
Thanks, looks like the latest version that works is 4.1.12... Things have been broken for a while. We should definitely report our issue and make sure they follow up on it (and we should include a link to the issue next to the version pinning)

**Comment by bsipocz** [comment]
OK, I'll add a pinning for 4.1.12, possibly in the open PR about the debug option, so we don't need to rerun travis that much. 

On the other hand, I'm not sure how old our issue is, as it seems that there is an unrelated http related on on 4.2.x (that may still hide our one).

Thanks for investigating.

**Pull request closed without merging**
