### PR TITLE
Remove requires and provides from setup.py

### PR DESCRIPTION
**Pull request by astrofrog**
As suggested by @embray in https://groups.google.com/forum/#!topic/astropy-dev/urYO8ckB2uM

### CODE REVIEW

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
It's kind a shame too since it does still show that info on PyPI and is reasonably useful in practice.  But at the end of the day it's not worth the confusion over these keywords.

**Comment by astrofrog** [comment]
@embray - should we actually add a comment to explain why they are missing in case anyone thinks about adding them back?

**Comment by embray** [comment]
If you want.  You could just link to my post where I explained it?  Or be terse and claim "they're deprecated"

**Pull request merged**
