### PR TITLE
Switch to container-based Travis infrastructure

### PR DESCRIPTION
**Pull request by astrofrog**
cc @bsipocz @mwcraig since you did this in other packages

@eteq @embray - any objections to this? I think most packages will be fine with using this and don't need sudo?

### CODE REVIEW

**Comment by mwcraig** [comment]
I think this makes sense. Maybe add a link to the white list of apt packages in the README or something: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Comment by mwcraig** [comment]
Was also thinking an email to astropy-dev about how to upgrade would be helpful -- I'll send out in a few hours, unless you want to do it before then.

**Comment by astrofrog** [comment]
@mwcraig - thanks, added the URL

**Comment by mwcraig** [comment]
Hearing no objections, I'm going to merge this...

**Pull request merged**
