### PR TITLE
Configparser fix import in docs/conf

### LINKED ISSUE #179: Error with distutils config ConfigParser again
This issue is related to #169 and #172 .

```
$ python setup.py build_sphinx
running build_sphinx
running build
running build_py
running build_ext
skipping 'packagename/example_c.c' Cython extension (up-to-date)
Running Sphinx v1.4.3
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/config.py", line 291, in __init__
    execfile_(filename, config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 46, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
Sphinx Documentation subprocess failed with return code 1
```

Looks like there's also this place where the import has to be fixed:
https://github.com/astropy/package-template/blame/master/docs/conf.py#L44

I think the fix has to be propagated (manually, sigh) to most affiilated packages?
At least I'm seeing the error with `gammapy` and `astroplan` master since today (not sure why this came up now).

cc @astrofrog @bsipocz @zblz

### PR DESCRIPTION
**Pull request by bsipocz**
This is to close #179.

Also updating helpers to 1.2 and minor gitignore addition.

### CODE REVIEW

**Comment by cdeil** [comment]
👍 

This fix will have to be propagated to all affiliated packages that used the package-template, or people will run into this issue one package at a time when they update to Python 3.5.2.
I'll do it for Gammapy now, but I don't have time to make the rounds for the other affiliated packages.

**Comment by cdeil** [comment]
Actually after merging this, I would be nice if  all affiliated packages would make a bugfix release.

Install is broken for all with Python 3.5.2 that used the package-template `setup.py`, e.g. `astroplan` and `wcsaxes`
```
$ pip install wcsaxes --user
Collecting wcsaxes
  Downloading wcsaxes-0.8.tar.gz (226kB)
    100% |████████████████████████████████| 235kB 348kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-4rruu3qv/wcsaxes/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-4rruu3qv/wcsaxes/

$ pip install astroplan --user
Collecting astroplan
  Downloading astroplan-0.1.tar.gz (246kB)
    100% |████████████████████████████████| 256kB 469kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-ufz8gwrb/astroplan/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-ufz8gwrb/astroplan/
```

cc @astrofrog @eteq

**Comment by bsipocz** [comment]
Actually I think it may be better to use six here, what do you think @astrofrog? (We couldn't do that in setup.py as it's third party, but we can easily do it in this file since it's bundled to astropy.)

**Comment by bsipocz** [comment]
Good point, I leave it as is then. (There is though an astropy import in ``packagename/conftest.py`` already).

**Comment by cdeil** [comment]
@astrofrog  - Merge?

(This works, and it's the same fix that's already merged for `setup.py`, so should be OK to merge and finish this up, no?)

**Comment by astrofrog** [comment]
Thanks @bsipocz!

**Pull request merged**
