### PR TITLE
Check if the entry_points section is present

### PR DESCRIPTION
**Pull request by saimn**
Related to https://github.com/nmearl/specutils/pull/19 : if a user of the package template removes the `[entry_points]` section, this breaks the setup. This error is easy to avoid with the check added here, instead of requiring that an empty section is present.

The PR is against the *cookiecutter* branch which I think is now in use ?

### CODE REVIEW

**Comment by Cadair** [comment]
I think I modified the templates so that the section was always present in the end, but this should still be there so that if the user manually removes it it still works.

**Comment by pllim** [comment]
👍 This has bitten me in the past, where I just commented it, but it was still extra work.

**Comment by bsipocz** [comment]
This looks OK to me too.

However, we need to improve the travis matrix and have more testing for the content (rather than for cookiecutter itself). E.g. is the template still works with python2, the docs and egg builds are working as before, etc. Before that one is sorted out, I would hold back merging any content related PRs.

**Comment by bsipocz** [comment]
Thanks @saimn.

**Pull request merged**
