### PR TITLE
TST: Test Python 3.7 on Appveyor

### PR DESCRIPTION
**Pull request by pllim**
This might be a bit more controversial... Address #354 but for Windows.

### CODE REVIEW

**Comment by bsipocz** [comment]
Why is this controversial?

**Comment by pllim** [comment]
Because `conda` is slower to catch up on Windows for new Python releases. :woman_shrugging:

**Comment by bsipocz** [comment]
Oh, I think that's fine. This is just a template, and packages can also use PIP_DEPENDENCIES instead of conda, and that should work (though we had issues with the wheels, too, but that's a separate question).

**Comment by pllim** [comment]
:crossed_fingers:

**Pull request merged**
