### PR TITLE
add credits on render

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman <nstarkman@protonmail.com>

### CODE REVIEW

**Comment by nstarman** [comment]
@pllim A simple credits.rst file is added. Tests work.

**Comment by pllim** [comment]
Thanks, I'll have to defer on others like @bsipocz , @Cadair , and @astrofrog to review this one.

**Comment by nstarman** [comment]
I need to add a credits file to this repo as well.

**Comment by nstarman** [comment]
Squashed 2 two commits

**Comment by nstarman** [comment]
gentle ping @bsipocz @Cadair @astrofrog

**Comment by pllim** [comment]
See https://github.com/astropy/package-template#deprecation-warning

**Pull request closed without merging**
