### PR TITLE
Update MANIFEST.in to global-exclude .pyc and .o files

### PR DESCRIPTION
**Pull request by larrybradley**
The main changes are to `global-exclude *.pyc *.o` instead of simply `exclude` and to `include CHANGES.rst`.

### CODE REVIEW

**Comment by embray** [comment]
:+1:

**Comment by cdeil** [comment]
:+1: 

@larrybradley Can you please add a line to `TEMPLATE_CHANGES.md`? This is important for people that manually update their affiliated package (see [docs](http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html#updating-to-the-latest-template-files)) to become aware of such changes.

**Comment by larrybradley** [comment]
@cdeil  I've updated `TEMPLATE_CHANGES.md`.  Thanks.

**Comment by cdeil** [comment]
:+1:  to merge!

**Comment by astrofrog** [comment]
@larrybradley - oops, this will need to be rebased due to the conflict in the changelog

**Comment by larrybradley** [comment]
@astrofrog Done!  (both commits skip `travis-ci`)

**Comment by astrofrog** [comment]
@larrybradley - thanks!

**Pull request merged**
