### PR TITLE
Change John to Joan

### PR DESCRIPTION
**Pull request by DougBurke**
This PR changes the example user name and email from "John Doe" to "Joan Doe".

### CODE REVIEW

**Comment by DougBurke** [comment]
It looks like the failures are nothing to do with this PR, but with the conda setup: https://travis-ci.org/astropy/package-template/jobs/174193235

**Comment by adrn** [comment]
¯\_(ツ)_/¯

Why does it need a gendered name in the first place? I would vote for something like this instead:
```
author = Author Name
author_email = someone@nowhere.com
```

**Comment by bsipocz** [comment]
@adrn - I'm glad someone else think this, too. Also hardly any package is a lone effort, what about suggesting ``packagename Contributors``. It's also easier to find with grepping and they advised to look for and change all occurrence of ``packagename``.

**Comment by DougBurke** [comment]
It seems like you (@bsipocz) have a better idea of what you want here than I do, so it probably makes more sense for you to open up a new PR than bother with this one.

**Comment by bsipocz** [comment]
@DougBurke - Thanks for identifying this at the first place. I'll let the others to decide which one they like more ``Author Name`` or ``packagename Contributors``.

**Comment by astrofrog** [comment]
I think ``Author Names`` - for <=5 contributors, I think it makes sense to list the main authors.

**Comment by bsipocz** [comment]
@DougBurke - Thanks for raising this issue, I've attached another commit to this branch to change the text to the one @astrofrog suggested.

**Pull request merged**
