### PR TITLE
(port to cookiecutter) Update conftest.py to reflect changes to test infrastructure

### PR DESCRIPTION
**Pull request by Cadair**
#282

### CODE REVIEW

**Comment by bsipocz** [comment]
Could you fix the travis failures? Otherwise this is good to go.

**Comment by astrofrog** [comment]
The issue is that hypothesis is installed, and it doesn't play well with non-dev astropy test collection

**Comment by Cadair** [comment]
Why is hypothesis installed?!

**Comment by Cadair** [comment]
Hypothesis seems to be getting pulled in by one of the core packages: https://travis-ci.org/astropy/package-template/jobs/308928110#L557

I have no idea why!

**Comment by drdavella** [comment]
@Cadair. @bsipocz, it's `pytest`:

>(testenv)  $ conda install pytest
Fetching package metadata ...........
Solving package specifications: .
>
>Package plan for installation in environment /home/dan/miniconda3/envs/testenv:
>
>The following NEW packages will be INSTALLED:
>
>    attrs:          17.3.0-py36h5ab58ff_0
    coverage:       4.4.2-py36hca7c4c5_0 
    hypothesis:     3.38.5-py36h196a6cc_0
    pluggy:         0.6.0-py36hb689045_0 
    py:             1.5.2-py36h29bf505_0 
    pympler:        0.5-py36h6b12e4d_0   
    pytest:         3.3.0-py36h23ce9bc_0 
    six:            1.11.0-py36h372c433_1
    zope:           1.0-py36_0           
    zope.interface: 4.4.3-py36h0ccbf34_0

**Comment by Cadair** [comment]
😱 hhhhhuuuuhhhhhhhhhhh

**Comment by Cadair** [comment]
curiously the conda-forge variant appears not to have that as a dep: https://github.com/conda-forge/pytest-feedstock/blob/master/recipe/meta.yaml

**Comment by drdavella** [comment]
Looks like maybe it gets pulled in transitively by `attrs`:
>(testenv)  $ conda install attrs   
Fetching package metadata ...........
Solving package specifications: .
>
>Package plan for installation in environment /home/dan/miniconda3/envs/testenv:
>
>The following NEW packages will be INSTALLED:
>
>    attrs:          17.3.0-py36h5ab58ff_0
    coverage:       4.4.2-py36hca7c4c5_0 
    hypothesis:     3.38.5-py36h196a6cc_0
    pympler:        0.5-py36h6b12e4d_0   
    zope:           1.0-py36_0           
    zope.interface: 4.4.3-py36h0ccbf34_0

**Pull request merged**
