### PR TITLE
Conftest configure

### PR DESCRIPTION
**Pull request by nstarman**
- the conftest code is given a doctoring from the top-level comments
- the `pytest_configure` function is likewise documented
- `import astropy.units as u` is auto-imported into docstring tests

### CODE REVIEW

**Comment by nstarman** [comment]
While I agree with Zen of Python line 2, I feel this is a somewhat special case. On the developer side, anyone writing example code in docstrings either sticks this in boilerplate code at the beginning of the section or, if it's critical, purposefully includes it with the specific example. While this doesn't change the latter, it nicely eliminates the former. Examples are just the core code.
On the user side, this feels like a standard import that astropy users just know, like `numpy -> np` (which actually might be a good fixture to add).

**Comment by embray** [comment]
I agree with @pllim : It's cool to see that this is *possible* (I did not know this) but I think it's too magical, implicit, confusing (a new user stumbling on a particular doc does not necessarily know where `np` or `u` came from).  It's also arbitrary bc I can think of several other "common imports" I would normally like to skip having to write when writing tests.  At the end of the day, using implicit magic is also too prone to hide mistakes.

**Comment by nstarman** [comment]
Okay. Outvoted 🙃. Not that this is a democracy. I'll drop the pytest auto-injections.

**Comment by nstarman** [comment]
#no-changelog-needed

**Review by astrofrog — COMMENTED** [review]
Thanks for the PR! Just out of curiosity what is the motivation for adding docstrings to the module and function? This file shouldn't appear in public API docs in general - pytest_configure for example is not something users should ever call directly, and the module should ideally be excluded from at API docs.

**Comment by nstarman** [comment]
It's mostly personal reference. Even for short code snippets, with python being such a dynamical language I like to know what I (or someone else) considered the scope of the function.

**Comment by embray** [comment]
I don't see a problem with it--actually I think it makes sense.   I think all modules should be documented with docstrings instead of comments, just for consistency's sake, even if it's not a docstring most people will ever see at runtime.

**Comment by embray** [comment]
This isn't doing anything more than adding the docstrings now, but I don't see the harm either.  Thanks @nstarman !  I'll try to follow up on some of your other PRs sooner rather than later.

**Pull request merged**
