### PR TITLE
Replace deprecated license_file option with license_files

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes the warning: `SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.`

### CODE REVIEW

**Comment by pllim** [comment]
Oh dear... CI needs clean up first.

**Comment by lpsinger** [comment]
Yup. Hopefully #524 will help.

**Comment by lpsinger** [comment]
Tests are passing now.

**Review by pllim — APPROVED** [review]
If CI passes, then fine by me. Thanks!

**Pull request merged**
