### PR TITLE
Update ez_setup.py to latest upstream version

### PR DESCRIPTION
**Pull request by larrybradley**
Removes tabs (gasp!) and an unused import from `ez_setup.py`.

### CODE REVIEW

**Comment by astrofrog** [comment]
@larrybradley - it might be better to fix these issues upstream. I think the official version is at https://bootstrap.pypa.io/ez_setup.py

**Comment by larrybradley** [comment]
It's already fixed upstream (https://github.com/pypa/setuptools/blob/bootstrap/ez_setup.py).  However, that file has some differences from the version currently in `package-template`.  Have we customized `ez_setup.py` in any way or can I simply copy the latest version here?

**Comment by astrofrog** [comment]
@larrybradley - I don't think we've customized it, so can you update the version here from the latest version?

**Comment by astrofrog** [comment]
You can also do it in the core package if you like. For info, the last time it was done in the core package was https://github.com/astropy/astropy/pull/4141.

**Comment by larrybradley** [comment]
Done.

Also updated in the core package:  https://github.com/astropy/astropy/pull/5004

**Comment by bsipocz** [comment]
Can we merge this pls? So I'll go ahead and update a few affil. packages to the latest template.

**Comment by astrofrog** [comment]
@bsipocz - done!

**Pull request merged**
