### PR TITLE
Update astropy-helpers v2.0

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - thanks! I think we may have to either drop Python 3.3 support in affiliated packages, or build astropy 2.0 with Python 3.3 in astropy-ci-extras - what do you think makes sense?

**Comment by bsipocz** [comment]
I think we need to drop 3.3 for any new templates as this is in line with the astropy version supports. Probably drop also 3.4 right now rather than wait with it a few months. 

Maintainers can always add back those manually if they wish, but the template should be cutting edge ;)

Anyway, I think this PR is problematic as it's not against the cookiecutter branch, I'll come back to it later this evening.

**Comment by bsipocz** [comment]
So now I've rebased this. With the cookiecutter, there is no astropy_helpers here, so couldn't update. I'll remove the template form the list of packages of the update script.

**Comment by bsipocz** [comment]
OK, I've found the json setting, so this is now indeed should update the helpers for new projects.

**Pull request merged**
