### PR TITLE
Adding coveragerc to MANIFEST

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
I also wonder where is ``astropy-helpers``?? There is ``ah_bootstrap.py`` both here and in the rendered version, but no sign of the helpers. I doubt that would be a working solution.

**Comment by eteq** [comment]
@bsipocz - I had the same question, and *thought* I solved it: if you run cookiecutter and don't have `gitpython` installed, there's this note:
```
gitpython is not installed so the repository will not be initialised and astropy_helpers not downloaded.
```

*however*, it looks like gitpython *is* there in the travis build (see e.g. https://travis-ci.org/astropy/package-template/jobs/237983659 ) - so why isn't it showing up?

**Comment by eteq** [comment]
Maybe it's something weird with how ``git add -A`` works?  That's how ``.travis-deply.sh`` seems to do it. @Cadair, any idea here?

**Comment by bsipocz** [comment]
Still, how would the cookiecutter know which version of helpers it needs? Surely we need include something in the template here, don't we?

**Comment by Cadair** [comment]
The version of `astropy_helpers` is set in the `cookiecutter.json` file and can be changed by the user during setup. (see here: https://github.com/astropy/package-template/blob/cookiecutter/hooks/post_gen_project.py#L51)

We should be copying `ah_bootstrap.py` out of the submodule once it is enabled so that the version is consistent. see #251

**Comment by bsipocz** [comment]
Still it's missing from the rendered branch. Anyway I'll open a new issue for it, but merge this PR.

**Pull request merged**
