### PR TITLE
Fix configparser in new python 3.5 [#169]

### LINKED ISSUE #169: ConfigParser incompatibility with new python 3.5
We got this reported in astroquery in https://github.com/astropy/astroquery/issues/691, but it's really belongs here to the template.

> For some reason, the module distutils.config of Python 3.5 has been modified to use RawConfigParser instead of ConfigParser (https://hg.python.org/cpython/rev/eae59b6bf133).
> As a consequence, astroquery fails to build with this version (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824170).
> 
> I suggest you stop using the config parser included in distutils.config to use directly the ConfigParser module.

cc @ViviCoder

### PR DESCRIPTION
**Pull request by zblz**
This is how I fixed the configparser problem in naima.

Fixes #169

### CODE REVIEW

**Comment by bsipocz** [comment]
I wonder the reason for using it from distutils at the first place. 

If there was none :+1: for this, though I think it would be slightly nicer to have one import from six.

**Comment by zblz** [comment]
Using `six` would be nicer, but ensuring it is installed whenever setup.py is run is non-trivial short of packaging it in package-template. I changed it to a `try: ... except ImportError: ...` block as is done in `ah_bootstrap.py` as I think it is more readable.

**Comment by astrofrog** [comment]
``setup.py`` can't depend on any third-party packages, so the fix here is correct

**Comment by cdeil** [comment]
I think conda now switched to Python 3.5.2 today, causing travis-ci installs to fail e.g. for Gammapy:
https://travis-ci.org/gammapy/gammapy/jobs/142512114#L317

@astrofrog - Can you make a reproject and APLPy release to fix this issue?

**Comment by bsipocz** [comment]
@cdeil - I've opened PRs to a handful of packages over the weekend, if you missing ones please ping me (the sample was quite random, included anything that I had a local clone).
 
Obviously the PRs only fix the issue, but the maintainers still have to do the releases.

**Pull request merged**
